
### version
GET {{urlbase}}/about

### activityGet
POST {{urlbase}}/activityGet
Content-Type: application/json

[
  {
    "id": "1"
  }
]

### activityPage
POST {{urlbase}}/activityPage
Content-Type: application/json

[
  {
    "offset": 0,
    "limit": 10
  }
]

### activityCreate
POST {{urlbase}}/activityCreate
Content-Type: application/json

[
  {
    "id": "1",
    "name": "1",
    "description": "1",
    "status": "NOT_STARTED"
  },
  {
    "id": "2",
    "name": "2",
    "description": "2",
    "status": "NOT_STARTED"
  },
  {
    "id": "3",
    "name": "3",
    "description": "3",
    "status": "NOT_STARTED"
  },
  {
    "id": "4",
    "name": "4",
    "description": "4",
    "status": "NOT_STARTED"
  }
]

### activityUpdate
POST {{urlbase}}/activityUpdate
Content-Type: application/json

[
  {
    "id": "1",
    "name": "1",
    "description": "11",
    "status": "NOT_STARTED"
  }
]

### assetCreate
POST {{urlbase}}/assetCreate
Content-Type: application/json

[
  {
    "id": "1",
    "name": "1",
    "description": "1",
    "status": "ISSUED"
  }
]

### assetUpdate
POST {{urlbase}}/assetUpdate
Content-Type: application/json

[
  {
    "id": "1",
    "name": "1",
    "description": "11",
    "status": "ASSIGNED"
  }
]

### assetUpdate
POST {{urlbase}}/assetUpdate
Content-Type: application/json

[
  {
    "id": "1",
    "name": "1",
    "description": "11",
    "status": "RETIRED"
  }
]

### assetGet
POST {{urlbase}}/assetGet
Content-Type: application/json

[
  {
    "id": "1"
  }
]

### assetPage
POST {{urlbase}}/assetPage
Content-Type: application/json

[
  {
    "offset": 0,
    "limit": 10
  }
]


### projectCreate
POST {{urlbase}}/projectCreate
Content-Type: application/json

[
  {
    "identifier": "2",
    "name": "33333",
    "description": "2"
  }
]

### projectCreate2
POST {{urlbase}}/projectCreate
Content-Type: application/json

[
  {
    "identifier": "56e421ca-621d-4e84-bd6d-93cb9dd25d53",
    "country": "Senegal",
    "creditingPeriodStartDate": 1679431411848,
    "creditingPeriodEndDate": 1679435486544,
    "description": "Descrption of the project Denali",
    "dueDate": 1679454287464,
    "estimatedReduction": "729747128",
    "localization": "Ulaanbaatar",
    "name": "Pumari Chhish",
    "proponentAccount": {
      "id": "632-97-5471",
      "name": "Kozey-Kirlin"
    },
    "proponent": "Description about the proponent",
    "type": "Type of the project",
    "referenceYear": "2023",
    "registrationDate": 1679429501984,
    "status": "STAMPED",
    "vintage": 2023.0,
    "slug": "slug",
    "creationDate": 1679429838,
    "lastModificationDate": 1679413438
  }

]

### projectUpdate
POST {{urlbase}}/projectUpdate
Content-Type: application/json

[
  {
    "id": "1",
    "name": "1",
    "description": "11",
    "status": "UNDER_REVIEW"
  }
]

### projectGet
POST {{urlbase}}/projectGet
Content-Type: application/json

[
  {
    "id": "42f905f8-42ec-4458-84e5-3a536f25b2fa"
  }
]

### projectPage
POST {{urlbase}}/projectPage
Content-Type: application/json

[
  {
    "offset": 0,
    "limit": 10,
    "name": "333"
  }
]


###
POST{{urlbaseCCCEV}}/requirementListChildrenByType
Content-Type: application/json

{
  "identifiers": ["P1", "P2", "P3", "P4", "P5"],
  "type": "Activities"
}

###
POST {{urlbase}}/activityStepEvidenceFulfill
Content-Type: multipart/form-data; boundary=your_boundary

--your_boundary
Content-Disposition: form-data; name="command"
Content-Type: application/json

{
    "certificationIdentifier": "yahumasud",
    "identifier": "B102",
    "isPublic": true
}

--your_boundary
Content-Disposition: form-data; name="file"; filename="HelloWorld.pdf"
Content-Type: application/pdf

< ./infra/asset/HelloWorld.pdf
--your_boundary--

###
POST {{urlbase}}/activityStepFulfill
Content-Disposition: form-data; name="command"
Content-Type: application/json

{
    "certificationIdentifier": "yahumasud",
    "identifier": "B102",
    "value": "test"
}

###

POST {{urlbase}}/assetTransactionPage
Content-Type: application/json

{
  "projectId": "e53f091c-bb37-4840-ad82-b16c65224f44"
}

###

POST {{urlbase}}/assetPoolCreate
Content-Type: application/json

{
  "projectId": "e53f091c-bb37-4840-ad82-b16c65224f44",
  "vintage": "2023",
  "granularity": 0.1
}

### projectGet
POST {{urlbase}}/projectGet
Content-Type: application/json

{
  "id": "e53f091c-bb37-4840-ad82-b16c65224f44"
}

### assetIssue
//4519f147-5a27-4474-9950-234c4aed87b6 poolId
POST {{urlbase}}/projectGet
Content-Type: application/json

{
  "poolId": "2ac68753-eb5e-4148-8dc2-40b741a350d4",
  "receiver": "SmartB",
  "quantity": 100
}


### cataloguePage
POST {{urlbase}}/cataloguePage
Content-Type: application/json

{
}
### cataloguePage
POST {{urlbase}}/catalogueGet
Content-Type: application/json

{
  "identifier": "standards"
}

### cataloguePage
POST {{urlbase}}/catalogueGet
Content-Type: application/json

{
  "identifier": "verra"
}

### cataloguePage
POST {{urlbase}}/catalogueGet
Content-Type: application/json

{
  "identifier": "standards-verra-programs"
}

### cataloguePage
POST {{urlbase}}/cataloguePage
Content-Type: application/json

{
  "parentIdentifier": "standards-verra-programs",
  "offset": 0,
  "limit": 4
}