# https://registry.trace.smart-b.io/projects/e53f091c-bb37-4840-ad82-b16c65224f44

### projectPage
#POST {{urlbase}}/projectPage
#Content-Type: application/json
#
#{}
#
#> {% client.global.set("projectId", response.body[0].items[0].id); %}


### projectGet
#POST {{urlbase}}/projectGet
#Content-Type: application/json
#
#{
#  "id": "{{assetProjectId}}"
#}

### assetTransactionPage
#POST {{urlbase}}/assetTransactionPage
#Content-Type: application/json
#
#{
#  "projectId": "{{assetProjectId}}"
#}

### OAuth2 Token Phease
POST {{urlAuth}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id={{offseter_clientId}}&client_secret={{offseter_clientSecret}}

> {% client.global.set("offseter_accessToken", response.body.access_token); %}

### OAuth2 Token Issuer
POST {{urlAuth}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id={{issuer_clientId}}&client_secret={{issuer_clientSecret}}

> {% client.global.set("issuer_accessToken", response.body.access_token); %}

### assetPoolCreate
POST {{urlbase}}/assetPoolCreate
Content-Type: application/json
Authorization: Bearer {{issuer_accessToken}}

{
  "vintage": "2013",
  "indicator": "carbon",
  "granularity": "0.001",
  "projectId": "{{assetProjectId}}"
}

> {% client.global.set("poolId", response.body[0].id); %}

### assetIssue
POST {{urlbase}}/assetIssue
Content-Type: application/json
Authorization: Bearer {{issuer_accessToken}}

{
  "poolId": "{{poolId}}",
  "to": "Rockfeller",
  "quantity": 10000
}

### assetTransfer
POST {{urlbase}}/assetTransfer
Content-Type: application/json
Authorization: Bearer {{issuer_accessToken}}

{
  "poolId": "{{poolId}}",
  "from": "Rockfeller",
  "to": "{{offseter}}",
  "quantity": 10000
}

#### assetOffset
POST {{urlbase}}/assetOffset
Content-Type: application/json
Authorization: Bearer {{offseter_accessToken}}

{
  "poolId": "{{poolId}}",
  "from": "{{offseter}}",
  "to": "Phease",
  "quantity": 0.001
}

#### assetOffset second
POST {{urlbase}}/assetOffset
Content-Type: application/json
Authorization: Bearer {{offseter_accessToken}}

{
  "poolId": "{{poolId}}",
  "from": "{{offseter}}",
  "to": "0x71C7656EC7ab88b098defB751B7401B5f6d8976F",
  "quantity": 42.141
}

### ShouldNotWork
POST {{urlbase}}/assetOffset
Content-Type: application/json
Authorization: Bearer {{offseter_accessToken}}

{
  "poolId": "{{poolId}}",
  "from": "ShouldNotWork",
  "to": "0x71C7656EC7ab88b098defB751B7401B5f6d8976F",
  "quantity": 42.141
}
