include:
  - project: 'framework/fixers/cicd'
    file: 'make/.gitlab-ci-jdk17.yml'

stages:
  - package

##########################################
## Tasks
##########################################
#  docker-gateway docker-web docker-registry-certificate-web
libs:
  stage: package
  extends:
    - .make
  variables:
    MAKE_TARGET: libs
    SNAPSHOT_SUFIX: "-SNAPSHOT"

api:
  stage: package
  extends:
    - .make
  variables:
    MAKE_TARGET: docker-gateway

web:
  stage: package
  extends:
    - .make
  variables:
    MAKE_TARGET: docker-web

docker-registry-certificate-web:
  stage: package
  extends:
    - .make
  variables:
    MAKE_TARGET: docker-registry-certificate-web

docs:
  stage: package
  extends:
    - .make
  variables:
    MAKE_TARGET: docs
