### version
GET https://api.registry.smartb.network/ver/about

### about
GET http://localhost:8070/api/about

### activityCreate
POST http://localhost:8070/api/activityCreate
Content-Type: application/json

[
  {
    "id": "1",
    "name": "1",
    "description": "1",
    "status": "NOT_STARTED"
  },
  {
    "id": "2",
    "name": "2",
    "description": "2",
    "status": "NOT_STARTED"
  },
  {
    "id": "3",
    "name": "3",
    "description": "3",
    "status": "NOT_STARTED"
  },
  {
    "id": "4",
    "name": "4",
    "description": "4",
    "status": "NOT_STARTED"
  }
]

### activityUpdate
POST http://localhost:8070/api/activityUpdate
Content-Type: application/json

[
  {
    "id": "1",
    "name": "1",
    "description": "11",
    "status": "NOT_STARTED"
  }
]

### activityGet
POST http://localhost:8070/api/activityGet
Content-Type: application/json

[
  {
    "id": "1"
  }
]

### activityPage
POST http://localhost:8070/api/activityPage
Content-Type: application/json

[
  {
    "offset": 0,
    "limit": 10
  }
]

### assetCreate
POST http://localhost:8070/api/assetCreate
Content-Type: application/json

[
  {
    "id": "1",
    "name": "1",
    "description": "1",
    "status": "ISSUED"
  }
]

### assetUpdate
POST http://localhost:8070/api/assetUpdate
Content-Type: application/json

[
  {
    "id": "1",
    "name": "1",
    "description": "11",
    "status": "ASSIGNED"
  }
]

### assetUpdate
POST http://localhost:8070/api/assetUpdate
Content-Type: application/json

[
  {
    "id": "1",
    "name": "1",
    "description": "11",
    "status": "RETIRED"
  }
]

### assetGet
POST http://localhost:8070/api/assetGet
Content-Type: application/json

[
  {
    "id": "1"
  }
]

### assetPage
POST http://localhost:8070/api/assetPage
Content-Type: application/json

[
  {
    "offset": 0,
    "limit": 10
  }
]


### projectCreate
POST http://localhost:8070/api/projectCreate
Content-Type: application/json

[
  {
    "id": "1",
    "name": "1",
    "description": "1",
    "status": "REGISTRATION_REQUESTED"
  }
]

### projectUpdate
POST http://localhost:8070/api/projectUpdate
Content-Type: application/json

[
  {
    "id": "1",
    "name": "1",
    "description": "11",
    "status": "UNDER_REVIEW"
  }
]

### projectGet
POST http://localhost:8070/api/projectGet
Content-Type: application/json

[
  {
    "id": "1"
  }
]

### projectPage
POST http://localhost:8070/api/projectPage
Content-Type: application/json

[
  {
    "offset": 0,
    "limit": 10
  }
]

### protocolCreate
POST http://localhost:8070/api/protocolCreate
Content-Type: application/json

[
  {
    "id": "2",
    "name": "1",
    "description": "1",
    "status": "UNDER_VALIDATION"
  }
]

### protocolUpdate
POST http://localhost:8070/api/protocolUpdate
Content-Type: application/json

[
  {
    "id": "2",
    "name": "1",
    "description": "11",
    "status": "VALIDATION_REQUESTED"
  }
]

### protocolGet
POST http://localhost:8070/api/protocolGet
Content-Type: application/json

[
  {
    "id": "1"
  }
]

### protocolPage
POST http://localhost:8070/api/protocolPage
Content-Type: application/json

[
  {
    "offset": 0,
    "limit": 10
  }
]

