
### version
GET {{urlbase}}/about



### activityGet
POST {{urlbase}}/activityGet
Content-Type: application/json

[
  {
    "id": "1"
  }
]

### activityPage
POST {{urlbase}}/activityPage
Content-Type: application/json

[
  {
    "offset": 0,
    "limit": 10
  }
]

### activityCreate
POST {{urlbase}}/activityCreate
Content-Type: application/json

[
  {
    "id": "1",
    "name": "1",
    "description": "1",
    "status": "NOT_STARTED"
  },
  {
    "id": "2",
    "name": "2",
    "description": "2",
    "status": "NOT_STARTED"
  },
  {
    "id": "3",
    "name": "3",
    "description": "3",
    "status": "NOT_STARTED"
  },
  {
    "id": "4",
    "name": "4",
    "description": "4",
    "status": "NOT_STARTED"
  }
]

### activityUpdate
POST {{urlbase}}/activityUpdate
Content-Type: application/json

[
  {
    "id": "1",
    "name": "1",
    "description": "11",
    "status": "NOT_STARTED"
  }
]

### assetCreate
POST {{urlbase}}/assetCreate
Content-Type: application/json

[
  {
    "id": "1",
    "name": "1",
    "description": "1",
    "status": "ISSUED"
  }
]

### assetUpdate
POST {{urlbase}}/assetUpdate
Content-Type: application/json

[
  {
    "id": "1",
    "name": "1",
    "description": "11",
    "status": "ASSIGNED"
  }
]

### assetUpdate
POST {{urlbase}}/assetUpdate
Content-Type: application/json

[
  {
    "id": "1",
    "name": "1",
    "description": "11",
    "status": "RETIRED"
  }
]

### assetGet
POST {{urlbase}}/assetGet
Content-Type: application/json

[
  {
    "id": "1"
  }
]

### assetPage
POST {{urlbase}}/assetPage
Content-Type: application/json

[
  {
    "offset": 0,
    "limit": 10
  }
]


### projectCreate
POST {{urlbase}}/projectCreate
Content-Type: application/json

[
  {
    "id": "1",
    "name": "1",
    "description": "1",
    "status": "REGISTRATION_REQUESTED"
  }
]

### projectUpdate
POST {{urlbase}}/projectUpdate
Content-Type: application/json

[
  {
    "id": "1",
    "name": "1",
    "description": "11",
    "status": "UNDER_REVIEW"
  }
]

### projectGet
POST {{urlbase}}/projectGet
Content-Type: application/json

[
  {
    "id": "1"
  }
]

### projectPage
POST {{urlbase}}/projectPage
Content-Type: application/json

[
  {
    "offset": 0,
    "limit": 10
  }
]

### protocolCreate
POST {{urlbase}}/protocolCreate
Content-Type: application/json

[
  {
    "id": "2",
    "name": "1",
    "description": "1",
    "status": "UNDER_VALIDATION"
  }
]

### protocolUpdate
POST {{urlbase}}/protocolUpdate
Content-Type: application/json

[
  {
    "id": "2",
    "name": "1",
    "description": "11",
    "status": "VALIDATION_REQUESTED"
  }
]

### protocolGet
POST {{urlbase}}/protocolGet
Content-Type: application/json

[
  {
    "id": "1"
  }
]

### protocolPage
POST {{urlbase}}/protocolPage
Content-Type: application/json

[
  {
    "offset": 0,
    "limit": 10
  }
]

