# https://registry.trace.smart-b.io/projects/e53f091c-bb37-4840-ad82-b16c65224f44

### projectPage
POST {{urlbase}}/projectPage
Content-Type: application/json

{
}

> {% client.global.set("projectId", response.body[0].items[0].id); %}


### projectGet
POST {{urlbase}}/projectGet
Content-Type: application/json

{
  "id": "{{projectId}}"
}

### assetTransactionPage
POST {{urlbase}}/assetTransactionPage
Content-Type: application/json

{
  "projectId": "{{projectId}}"
}

### OAuth2 Token Phease
POST https://auth.connect.smart-b.io/realms/sb-dev/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id={{phease_clientId}}&client_secret={{phease_clientSecret}}

> {% client.global.set("phease_accessToken", response.body.access_token); %}

### OAuth2 Token Rockfeller
POST https://auth.connect.smart-b.io/realms/sb-dev/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id={{rockfeller_clientId}}&client_secret={{rockfeller_clientSecret}}

> {% client.global.set("rockfeller_accessToken", response.body.access_token); %}

### assetPoolCreate
POST {{urlbase}}/assetPoolCreate
Content-Type: application/json
Authorization: Bearer {{rockfeller_accessToken}}

{
  "vintage": "2012",
  "indicator": "tonnes",
  "granularity": "0.001",
  "projectId": "{{projectId}}"
}

> {% client.global.set("poolId", response.body[0].id); %}

### assetIssue
POST {{urlbase}}/assetIssue
Content-Type: application/json
Authorization: Bearer {{rockfeller_accessToken}}

{
  "poolId": "{{poolId}}",
  "to": "Rockfeller",
  "quantity": 50000
}

### assetTransfer
POST {{urlbase}}/assetTransfer
Content-Type: application/json
Authorization: Bearer {{rockfeller_accessToken}}

{
  "poolId": "{{poolId}}",
  "from": "Rockfeller",
  "to": "Phease",
  "quantity": 10000
}

### assetOffset
POST {{urlbase}}/assetOffset
Content-Type: application/json
Authorization: Bearer {{phease_accessToken}}

{
  "poolId": "{{poolId}}",
  "from": "Phease",
  "to": "0x5f5Afce1f980cBae2cEaf7Ec1696b0AEb8dE0366",
  "quantity": 20
}
