version: "3.7"
services:
  redis:
    image: redis/redis-stack:6.2.6-v0
    ports:
      - "6379:6379"
      - "8011:8001"
  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - '8001:8001'

networks:
  bclannet-it:
    name: bclannet-it
    external: true

