version: "3.7"

services:
  tr-registry-script:
    container_name: tr-registry-script
    image: smartbcity/tr-registry-script:next
    environment:
      - registry_script_retry_max=5
      - registry_script_retry_delayMillis=10000
      - registry_script_init_auth_url=https://auth.dev.connect.smart-b.io/realms/sb-dev
      - registry_script_init_cccev_url=http://${CCCEV_HOST_NAME}:${CCCEV_PORT}
      - registry_script_init_orchestrator_name=Smartb
      - registry_script_init_orchestrator_clientId=tr-registry-script-api
      - registry_script_init_orchestrator_clientSecret=***REMOVED***
    networks:
      - net

networks:
  net:
    name: ${DOCKER_NETWORK}
    external: true
