version: "3.7"

services:
  tr-registry-script:
    container_name: tr-registry-script
    image: smartbcity/tr-registry-script:experimental
    environment:
      - registry_script_retry_max=5
      - registry_script_retry_delayMillis=10000
      - registry_script_init_auth_url=https://auth.dev.connect.smart-b.io/realms/sb-dev
      - registry_script_init_cccev_url=https://dev.trace.smart-b.io/cccev
      - registry_script_init_registry_url=https://dev.trace.smart-b.io/ver
      - registry_script_init_orchestrator_name=Smartb
      - registry_script_init_orchestrator_clientId=tr-smartb-ver-app
      - registry_script_init_orchestrator_clientSecret=***REMOVED***
      - registry_script_init_nbProject=25
