version: "3.7"
services:
  fs-gateway:
    container_name: fs-gateway
    image: smartbcity/fs-gateway:${CONNECT_FS_VERSION}
    environment:
      - fs_s3_internal-url=http://minio:9000
      - fs_s3_external-url=http://localhost:9000
      - fs_s3_bucket=certification
      - fs_init_buckets=certification
      - fs_kb_url=${KB_HOST_NAME}
      - debug=true
    ports:
      - "8090:8090"
    networks:
      - bclannet-it

  minio:
    image: minio/minio:RELEASE.2022-02-26T02-54-46Z.fips
    container_name: minio
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
      - MINIO_SERVER_URL=http://minio:9000
      - MINIO_BROWSER=on
    command: server /data --console-address ":9003"
    ports:
      - "9000:9000"
      - "9003:9003"
    volumes:
      - minio:/data
    networks:
      - bclannet-it

volumes:
  minio:

networks:
  bclannet-it:
    name: bclannet-it
    external: true
