version: "3.7"
services:
  redis:
    image: redis/redis-stack:6.2.6-v0
    container_name: verr-redis
    ports:
      - 6379:6379
      - 8011:8001
    environment:
      REDISEARCH_ARGS: MINPREFIX 1 MAXPREFIXEXPANSIONS 1000
  #    volumes:
  #      - ~/DockerVolumes/redis/verr/data:/data
  redis-test:
    image: redis/redis-stack:6.2.6-v0
    container_name: verr-redis-test
    ports:
      - 6380:6379
      - 8012:8001
    environment:
      REDISEARCH_ARGS: MINPREFIX 1 MAXPREFIXEXPANSIONS 1000
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: verr-redisinsight
    ports:
      - '8001:8001'

networks:
  bclannet-it:
    name: bclannet-it
    external: true
