version: "3.7"

services:
  kb-api:
    container_name: kb-api
    image: smartbcity/kb:${KB_VERSION}
    ports:
      - "9999:9999"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL_NAME=gpt-3.5-turbo
      - CHROMADB_PERSIST_DIRECTORY=/chroma
    volumes:
      - kb_files:/chroma
    networks:
      - net

volumes:
  kb_files:

networks:
  net:
    name: ${DOCKER_NETWORK}
    external: true
