server:
  port: 8070

#spring:
#  webflux:
#    multipart:
#      maxInMemorySize: 20MB
#      maxHeadersSize: 20MB

cccev:
  url: http://localhost:8083

fs:
  url: http://localhost:8090

im:
  url: https://connect.smart-b.io/im
  organization:
    insee:
      token: c6ef3de5-3ef1-330a-8917-21f6750dcb09
      sirene-api: https://api.insee.fr/entreprises/sirene/V3

i2:
  issuers:
    -
      name: connect-sb-io
      authUrl: https://auth.connect.smart-b.io
      realm: connect
      web:
        clientId: sb-plateform-web
      im:
        clientId: sb-plateform-app
        clientSecret: secretsecret

ssm:
  signer:
    user:
      name: ssm-admin
      key: user/ssm-admin
    admin:
      name: ssm-admin
      key: user/ssm-admin
  couchdb:
    url: http://localhost:5984
    username: couchdb
    password: couchdb
    serviceName: s2-sample-did
  chaincode:
    url: http://localhost:9090

---
spring:
  config:
    activate:
      on-profile: init

server:
  port: 8000

---
spring:
  config:
    activate:
      on-profile: local

#i2:
#  issuers:
#    -
#      name: local
#      authUrl: http://localhost:8080/auth/
#      realm: alveole
#      web:
#        clientId: alveole-web
#      im:
#        clientId: alveole-api
#        clientSecret: ***REMOVED***
